name: Benchmark
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Benchmark
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build --progress=plain -t pyenv-virtualenv .
      - name: conda
        run: |
          docker run --rm --workdir /app -v $(pwd):/app pyenv-virtualenv bash build-conda.sh
      - name: pyenv + virtualenv
        run: |
          docker run --rm --workdir /app -v $(pwd):/app pyenv-virtualenv bash build-virtualenv.sh
